"""
Regression test for core/scorer.py against the notebook's own verification
cases (NFR-1). This is the test that must never be weakened to make a
change "pass" — if the scorer's output drifts from these six cases, the
scorer is wrong, not the test.

The reference cases live inside the model artifact itself
(data/Baku_XGBoost_Dashboard_Data.json -> "verification"), generated by the
training notebook's own Python xgboost.predict_proba call.
"""

import json
from pathlib import Path

import pytest

from core.scorer import score_inputs

ARTIFACT_PATH = Path(__file__).parents[2] / "data" / "Baku_XGBoost_Dashboard_Data.json"


@pytest.fixture(scope="module")
def verification_cases():
    with open(ARTIFACT_PATH) as f:
        return json.load(f)["verification"]


@pytest.mark.parametrize(
    "case_name",
    ["baseline", "finish-1.0", "finish-5.0", "finish-12.0", "finish-20.0", "missing-inputs"],
)
def test_scorer_matches_notebook_reference_case(verification_cases, case_name):
    """For each reference case, scoring the case's `inputs` through
    core/scorer.py must reproduce its `raw_scores` (and derived
    `win_scores`) within a tight numeric tolerance."""
    case = next(c for c in verification_cases if c["name"] == case_name)
    result = score_inputs(case["inputs"], str(ARTIFACT_PATH))

    assert result.raw_scores == pytest.approx(case["raw_scores"], abs=1e-5)
    assert result.win_scores == pytest.approx(case["win_scores"], abs=1e-5)
